### ISSUE TITLE
phonegap build not working with this plugin

### ISSUE THREAD

**Issue by mujaffars** [ratson/cordova-plugin-admob-free#174]
I am using admob-free since long but from Yesterday I am not able to create apk with phonegap build. I have added <gap:plugin name="cordova-plugin-admob-free" source="npm" /> in config.xml. But build giving below error

`/project/src/name/ratson/cordova/admob/banner/BannerListener.java:5: error: package com.google.android.gms.ads does not exist
import com.google.android.gms.ads.AdListener;
                                 ^
/project/src/name/ratson/cordova/admob/banner/BannerListener.java:12: error: cannot find symbol
class BannerListener extends AdListener {
                             ^
  symbol: class AdListener
/project/src/name/ratson/cordova/admob/banner/BannerExecutor.java:9: error: package com.google.android.gms.ads does not exist
import com.google.android.gms.ads.AdView;
                                 ^
/project/src/name/ratson/cordova/admob/AbstractExecutor.java:3: error: package com.google.android.gms.ads does not exist
import com.google.android.gms.ads.AdRequest;
                                 ^
/project/src/name/ratson/cordova/admob/banner/BannerExecutor.java:26: error: cannot find symbol
    private AdView adView;
            ^
  symbol:   class AdView
  location: class BannerExecutor
/project/src/name/ratson/cordova/admob/AdMob.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/project/src/name/ratson/cordova/admob/AdMob.java:8: error: package com.google.ads.mediation.admob does not exist
import com.google.ads.mediation.admob.AdMobAdapter;
                                     ^
/project/src/name/ratson/cordova/admob/AdMob.java:9: error: package com.google.android.gms.ads does not exist
import com.google.android.gms.ads.AdRequest;
                                 ^
/project/src/name/ratson/cordova/admob/AdMob.java:10: error: package com.google.android.gms.common does not exist
import com.google.android.gms.common.ConnectionResult;
                                    ^
/project/src/name/ratson/cordova/admob/AdMob.java:11: error: package com.google.android.gms.common does not exist
import com.google.android.gms.common.GoogleApiAvailability;
                                    ^
/project/src/name/ratson/cordova/admob/AdMobConfig.java:6: error: package com.google.android.gms.ads does not exist
import com.google.android.gms.ads.AdSize;
                                 ^
/project/src/name/ratson/cordova/admob/interstitial/InterstitialExecutor.java:5: error: package com.google.android.gms.ads does not exist
import com.google.android.gms.ads.InterstitialAd;
                                 ^
/project/src/name/ratson/cordova/admob/rewardvideo/RewardVideoExecutor.java:6: error: package com.google.ads.mediation.admob does not exist
import com.google.ads.mediation.admob.AdMobAdapter;
                                     ^
/project/src/name/ratson/cordova/admob/rewardvideo/RewardVideoExecutor.java:7: error: package com.google.android.gms.ads does not exist
import com.google.android.gms.ads.AdRequest;
                                 ^
/project/src/name/ratson/cordova/admob/rewardvideo/RewardVideoExecutor.java:8: error: package com.google.android.gms.ads does not exist
import com.google.android.gms.ads.MobileAds;
                                 ^
/project/src/name/ratson/cordova/admob/rewardvideo/RewardVideoExecutor.java:9: error: package com.google.android.gms.ads.reward does not exist
import com.google.android.gms.ads.reward.RewardedVideoAd;`

Anyone can help?
@ratson Please fix the issue

**Comment by MBuchalik** [comment]
Which version of PGB are you using? 
In your config.xml, look for a line looking like this:
``` xml
<preference name="phonegap-version" value="cli-(version)" />
```

**Comment by mujaffars** [comment]
@MBuchalik I have not incuded that, But phonegap by default taking it as "cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)", Did I need to specify specific version? Let me know

**Comment by MBuchalik** [comment]
I have successfully created a (test) build using cli-7.1.0 and builder 2. Does that work for you as well? If not, try to remove all plugins except cordova-plugin-admob-free. Maybe, there is a conflict with another plugin?

**Comment by mujaffars** [comment]
@MBuchalik using cli-7.1.0 and builder 2 Works. Thank you for helping 

Closing this ticket
